### ISSUE TITLE
checksum with binary files returns linecount error

### ISSUE THREAD

**Issue by HongChenTW** [weizard/fops#2]
Hi @weizard, this is Hong from Trend Micro, thanks for your time for developing this project.

I executed all subcommands and discovered a issue with `checksum`:

### execute

```sh
./bin/fops checksum -f test/lines_test
```
### return 

```
error:  Cannot do linecount for binary file 'test/lines_test'
```

`fops` should have ability to checksum binary files.

**Comment by weizard** [comment]
fixed, thanks for reported.

**Comment by HongChenTW** [comment]
Fix verified, thanks!
