### ISSUE TITLE
better error handling

### ISSUE THREAD

**Issue by rybbchao** [weizard/fops#3]
It is not a good idea you compare the error messages to check if the file exists, eg: [fops/files.go#L15](https://github.com/weizard/fops/blob/main/pkg/file/file.go#L15).
Try using `errors.Is()` or error comparison functions built in `os` package.

**Comment by weizard** [comment]
updated it, thanks

**Comment by rybbchao** [comment]
Reviewed, thanks for the fix. Closed now.
